# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
#
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

   
[[main]]
  name = "about"
  pageRef = "about"
  #url = "/about/"
  #especifica una URL a la que apunta el elemento del menú, 
  #no necesariamente corresponde a una página generada por Hugo 
  weight = 10

# descomentar el menú de blog en inglés, pero no el de url
#[[main]]
 # name = "notes"
 # pageRef = "notes"
        #url = "/blog/" 
 # weight = 20
 

[[main]]
  name = "cv"
  pageRef = "cv"
  #url = "/cv/"
  weight = 30

############

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"

[[main]]
  identifier = "locale"
  weight = 100
  [main.params]
  action = "locale"

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

#[[footer]]
#  name = "Tags"
#   pageRef = "tags"
#   weight = 10

#[[footer]]
#identifier = "locale"
 # weight = 100
  # [footer.params]
   # action = "locale"  
 