# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/configuration/#theme-parameters

colorScheme = "Fire" # ver más temas en https://jpanther.github.io/congo/docs/getting-started/#colour-schemes
defaultAppearance = "dark" # valid options: light or dark
autoSwitchAppearance = true

#defaultThemeColor = "#FFFFFF"
defaultThemeColor = "#FF5733"

enableSearch = true
enableCodeCopy = true
enableImageLazyLoading = true
enableImageWebp = true

# robots = ""
fingerprintAlgorithm = "sha256"

# estas dos lineas están también en el config.toml
description = "Research & Development"
# logo = "img/logoc.png" # cuando ejecuto HUGO, esta linea me dió un warning, se puede eliminar
# WARN  [CONGO] Theme parameter `logo` has been renamed to `header.logo`. Please update your site configuration.

[header]
  layout = "hybrid" # valid options: basic, hamburger, hybrid, custom
  logo = "img/logo.png"
  logoDark = "img/logo.png"
  showTitle = false

[footer]
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile" # valid options: page, profile, custom
  showRecent = false
  recentLimit = 5

[article]
  showDate = true
  showDateUpdated = false
  showAuthor = true
  showBreadcrumbs = false
  showDraftLabel = true
  showEdit = false
  #editURL = "https://github.com/marianocaruso/"
  editAppendPath = true
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = false
  showWordCount = false
  showComments = false
  sharingLinks = ["x-twitter", "linkedin", "telegram", "email"]

[list]
  showBreadcrumbs = false
  showSummary = false
  showTableOfContents = false
  showTaxonomies = false
  groupByYear = true
  paginationWidth = 1

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true

[fathomAnalytics]
  # site = "ABC12345"

[plausibleAnalytics]
  # domain = "blog.yoursite.com"
  # event = ""
  # script = ""

#[umamiAnalytics]
#  site = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
#  region = "eu"  # can be either "eu" or "us"

[verification]
  google = "SYbm-03Dwh4PbppJZdMEszrv-x0p59MhJ5XRzun7_o8"
  # bing = ""
  # pinterest = ""
  # yandex = ""
